# Generated by Django 6.0.2 on 2026-03-12 22:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('quote_number', models.CharField(blank=True, max_length=50, verbose_name='Quote Number')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Customer Email')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Customer Phone')),
                ('customer_address', models.TextField(blank=True, verbose_name='Customer Address')),
                ('related_lead', models.UUIDField(blank=True, help_text='UUID of the related lead', null=True, verbose_name='Related Lead')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('terms', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount Amount')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Converted At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes_quote',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('line_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Type')),
                ('product_id', models.UUIDField(blank=True, help_text='UUID of the referenced product', null=True, verbose_name='Product')),
                ('service_id', models.UUIDField(blank=True, help_text='UUID of the referenced service', null=True, verbose_name='Service')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Price')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Discount %')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Tax Rate %')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotes.quote', verbose_name='Quote')),
            ],
            options={
                'verbose_name': 'Quote Line',
                'verbose_name_plural': 'Quote Lines',
                'db_table': 'quotes_line',
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('prefix', models.CharField(max_length=10, verbose_name='Prefix')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Next Number')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Series')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('number_digits', models.PositiveSmallIntegerField(default=5, verbose_name='Number Digits')),
            ],
            options={
                'verbose_name': 'Quote Series',
                'verbose_name_plural': 'Quote Series',
                'db_table': 'quotes_series',
                'ordering': ['prefix'],
                'abstract': False,
                'unique_together': {('hub_id', 'prefix')},
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.quoteseries', verbose_name='Series'),
        ),
        migrations.CreateModel(
            name='QuoteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('default_validity_days', models.PositiveIntegerField(default=30, verbose_name='Default Validity (days)')),
                ('default_notes', models.TextField(blank=True, help_text='Default notes included in new quotes', verbose_name='Default Notes')),
                ('default_terms', models.TextField(blank=True, help_text='Default terms and conditions for quotes', verbose_name='Default Terms')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='Default Tax Rate %')),
                ('show_tax', models.BooleanField(default=True, help_text='Show tax breakdown on quotes', verbose_name='Show Tax')),
                ('show_discount', models.BooleanField(default=True, help_text='Show discount column on quotes', verbose_name='Show Discount')),
                ('default_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quotes.quoteseries', verbose_name='Default Series')),
            ],
            options={
                'verbose_name': 'Quote Settings',
                'verbose_name_plural': 'Quote Settings',
                'db_table': 'quotes_settings',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['hub_id', 'quote_number'], name='quotes_quot_hub_id_ada30a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['hub_id', 'status'], name='quotes_quot_hub_id_e9d030_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['hub_id', 'valid_until'], name='quotes_quot_hub_id_2b7d8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotesettings',
            unique_together={('hub_id',)},
        ),
    ]
